---

- name: This task only serves as a template for the tasks below
  ansible.builtin.set_fact:
    ignoreme: &task
      name: "{{ vars.taskid }}: {{ vars.name }}"
      register: task
      when:
        - "vars.taskid not in maintenance_exclude_tasks"
        - "maintenance_only is not defined or maintenance_only == vars.taskid"
  vars:
    taskid: ignoreme
    name: bar

- <<: *task
  vars:
    taskid: 14-001
    name: "Apparmor: Check if apparmor is enabled and enforcing apparmor_status"
  ansible.builtin.command: aa-status
  register: apparmor_status_output
  changed_when: false
  failed_when: false

- <<: *task
  vars:
    taskid: 14-002
    name: "Check if the system is properly registered at SUSE SUSEConnect --status-text"
  ansible.builtin.command: SUSEConnect --status-text
  register: suseconnect_status_output
  changed_when: "'Not Registered' in suseconnect_status_output.stdout"

- <<: *task
  vars:
    taskid: 14-003
    name: "Zypper: Update package lists and check for errors zypper refresh"
  ansible.builtin.command: zypper refresh
  register: zypper_refresh_output
  changed_when: false
  ignore_errors: "{{ zypper_refresh_output.rc != 0 }}"

- <<: *task
  vars:
    taskid: 14-004
    name: "Zypper: Check for available updates and review them zypper list-updates"
  ansible.builtin.command: zypper list-updates
  register: zypper_updates_output
  changed_when: false
  failed_when: false

- <<: *task
  vars:
    taskid: 14-005
    name: "Zypper: Check for orphaned packages but do not uninstall them if not needed anymore zypper packages --orphaned"
  ansible.builtin.command: zypper packages --orphaned
  register: zypper_orphaned_output
  changed_when: false
  failed_when: false
