---

- name: This task only serves as a template for the tasks below
  ansible.builtin.set_fact:
    ignoreme: &task
      name: "{{ vars.taskid }}: {{ vars.name }}"
      register: task
      when:
        - "vars.taskid not in maintenance_exclude_tasks"
        - "maintenance_only is not defined or maintenance_only == vars.taskid"
  vars:
    taskid: ignoreme
    name: bar

- <<: *task
  vars:
    taskid: 14-001
    name: "Apparmor: Check if apparmor is enabled and enforcing apparmor_status"
  ansible.builtin.command: aa-status
  register: apparmor_status_output
  changed_when: false
  failed_when: false

- <<: *task
  vars:
    taskid: 14-001
    name: "Apparmor: Check if apparmor is enabled and enforcing apparmor_status"
  ansible.builtin.debug:
    msg: "{{ apparmor_status_output.stdout }}"
  when: apparmor_status_output is succeeded

- <<: *task
  vars:
    taskid: 14-002
    name: "Check if the system is properly registered at SUSE SUSEConnect --status-text"
  ansible.builtin.command: SUSEConnect --status-text
  register: suseconnect_status_output
  changed_when: "'Not Registered' in suseconnect_status_output.stdout"

- <<: *task
  vars:
    taskid: 14-003
    name: "Zypper: Update package lists and check for errors zypper refresh"
  community.general.zypper:
    name: '*'
    update_cache: true
  register: zypper_refresh_output
  failed_when: "{{ zypper_refresh_output.rc != 0 }}"

- <<: *task
  vars:
    taskid: 14-004
    name: "Zypper: Check for available updates and review them zypper list-updates"
  community.general.zypper:
    name: '*'
    state: latest
  check_mode: true
  register: zypper_updates_output

- <<: *task
  vars:
    taskid: 14-005
    name: "Zypper: Check for orphaned packages but do not uninstall them if not needed anymore zypper packages --orphaned"
  ansible.builtin.command: zypper packages --orphaned
  register: sles_packages_status
  check_mode: false
  changed_when: false
  failed_when: "sles_packages_status.rc not in [0, 1]"

- <<: *task
  vars:
    taskid: 14-005
    name: "Zypper: Check for orphaned packages but do not uninstall them if not needed anymore zypper packages --orphaned"
  ansible.builtin.debug:
    var: "sles_packages_status.stdout_lines"
  changed_when: "sles_packages_status.stdout_lines | length > 0"
