---

maintenance_global_exclude_tasks: []
maintenance_host_exclude_tasks: []
maintenance_exclude_tasks: "{{ maintenance_global_exclude_tasks + maintenance_host_exclude_tasks }}"

# Define defaults which can be overriden on a host-by-host basis
