---

- name: Run automated maintenance tasks
  hosts: all
  tasks:

    - name: Apply checklists
      ansible.builtin.include_role:
        name: "adfinis.maintenance.{{ checklist_group }}"
      when: "inventory_hostname in groups[checklist_group]"
      loop: "{{ groups | map('regex_search', '^maintenance_[0-9]+_.*') | select | list }}"
      loop_control:
        loop_var: checklist_group
