---

name: Ansible Galaxy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Upload collection to Ansible Galaxy
      uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
